In [24]:
#import module pandas
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics import mean_absolute_error

#read data
df_test = pd.read_csv('/content/ALS_TestingData_78.csv')
df_train = pd.read_csv('/content/ALS_TrainingData_2223.csv')

In [25]:
df_test.head() #first few rows

   ID   Age_mean  ...  White.Blood.Cell..WBC._min  White.Blood.Cell..WBC._range
0   3  65.906849  ...                        6.60                      0.016148
1   4  54.000000  ...                        4.97                      0.006703
2   5  56.394521  ...                        5.01                      0.005410
3   6  72.619178  ...                        4.96                      0.076495
4   9  65.000000  ...                        7.94                      0.008507

[5 rows x 131 columns]

In [26]:
df_train.head()

   ID  Age_mean  Albumin_max  ...  Urine.Ph_max  Urine.Ph_median  Urine.Ph_min
0   1        65         57.0  ...           6.0              6.0           6.0
1   2        48         45.0  ...           7.0              5.0           5.0
2   3        38         50.0  ...           6.0              5.0           5.0
3   4        63         47.0  ...           7.0              6.0           5.0
4   5        63         47.0  ...           6.0              5.0           5.0

[5 rows x 101 columns]

In [27]:
#describe
df_test.describe()

               ID  ...  White.Blood.Cell..WBC._range
count   78.000000  ...                     78.000000
mean    51.589744  ...                      0.012203
std     28.468910  ...                      0.014724
min      3.000000  ...                      0.003078
25%     27.250000  ...                      0.005658
50%     51.500000  ...                      0.008402
75%     74.750000  ...                      0.012471
max    100.000000  ...                      0.092045

[8 rows x 131 columns]

In [28]:
df_train.describe()

                ID     Age_mean  ...  Urine.Ph_median  Urine.Ph_min
count  2223.000000  2223.000000  ...      2223.000000   2223.000000
mean   1214.874944    54.550157  ...         5.710639      5.183221
std     696.678300    11.396546  ...         0.625039      0.437222
min       1.000000    18.000000  ...         5.000000      5.000000
25%     614.500000    47.000000  ...         5.000000      5.000000
50%    1213.000000    55.000000  ...         6.000000      5.000000
75%    1815.500000    63.000000  ...         6.000000      5.000000
max    2424.000000    81.000000  ...         9.000000      8.000000

[8 rows x 101 columns]

In [29]:
df_train.columns.values

array(['ID', 'Age_mean', 'Albumin_max', 'Albumin_median', 'Albumin_min',
       'Albumin_range', 'ALSFRS_slope', 'ALSFRS_Total_max',
       'ALSFRS_Total_median', 'ALSFRS_Total_min', 'ALSFRS_Total_range',
       'ALT.SGPT._max', 'ALT.SGPT._median', 'ALT.SGPT._min',
       'ALT.SGPT._range', 'AST.SGOT._max', 'AST.SGOT._median',
       'AST.SGOT._min', 'AST.SGOT._range', 'Bicarbonate_max',
       'Bicarbonate_median', 'Bicarbonate_min', 'Bicarbonate_range',
       'Blood.Urea.Nitrogen..BUN._max',
       'Blood.Urea.Nitrogen..BUN._median',
       'Blood.Urea.Nitrogen..BUN._min', 'Blood.Urea.Nitrogen..BUN._range',
       'bp_diastolic_max', 'bp_diastolic_median', 'bp_diastolic_min',
       'bp_diastolic_range', 'bp_systolic_max', 'bp_systolic_median',
       'bp_systolic_min', 'bp_systolic_range', 'Calcium_max',
       'Calcium_median', 'Calcium_min', 'Calcium_range', 'Chloride_max',
       'Chloride_median', 'Chloride_min', 'Chloride_range',
       'Creatinine_max', 'Creatinine_median', 'Creatinine_min',
       'Creatinine_range', 'Gender_mean', 'Glucose_max', 'Glucose_median',
       'Glucose_min', 'Glucose_range', 'hands_max', 'hands_median',
       'hands_min', 'hands_range', 'Hematocrit_max', 'Hematocrit_median',
       'Hematocrit_min', 'Hematocrit_range', 'Hemoglobin_max',
       'Hemoglobin_median', 'Hemoglobin_min', 'Hemoglobin_range',
       'leg_max', 'leg_median', 'leg_min', 'leg_range', 'mouth_max',
       'mouth_median', 'mouth_min', 'mouth_range', 'onset_delta_mean',
       'onset_site_mean', 'Platelets_max', 'Platelets_median',
       'Platelets_min', 'Potassium_max', 'Potassium_median',
       'Potassium_min', 'Potassium_range', 'pulse_max', 'pulse_median',
       'pulse_min', 'pulse_range', 'respiratory_max',
       'respiratory_median', 'respiratory_min', 'respiratory_range',
       'Sodium_max', 'Sodium_median', 'Sodium_min', 'Sodium_range',
       'SubjectID', 'trunk_max', 'trunk_median', 'trunk_min',
       'trunk_range', 'Urine.Ph_max', 'Urine.Ph_median', 'Urine.Ph_min'],
      dtype=object)

In [30]:
df_test.columns.values

array(['ID', 'Age_mean', 'Albumin_max', 'Albumin_median', 'Albumin_min',
       'Albumin_range', 'ALSFRS_slope', 'ALSFRS_Total_max',
       'ALSFRS_Total_median', 'ALSFRS_Total_min', 'ALSFRS_Total_range',
       'ALT.SGPT._max', 'ALT.SGPT._median', 'ALT.SGPT._min',
       'ALT.SGPT._range', 'AST.SGOT._max', 'AST.SGOT._median',
       'AST.SGOT._min', 'AST.SGOT._range', 'Basophils_max',
       'Basophils_median', 'Basophils_min', 'Basophils_range',
       'Bicarbonate_max', 'Bicarbonate_median', 'Bicarbonate_min',
       'Bicarbonate_range', 'Bilirubin..total._max',
       'Bilirubin..total._median', 'Bilirubin..total._min',
       'Bilirubin..total._range', 'Blood.Urea.Nitrogen..BUN._max',
       'Blood.Urea.Nitrogen..BUN._median',
       'Blood.Urea.Nitrogen..BUN._min', 'Blood.Urea.Nitrogen..BUN._range',
       'BMI_max', 'bp_diastolic_max', 'bp_diastolic_median',
       'bp_diastolic_min', 'bp_diastolic_range', 'bp_systolic_max',
       'bp_systolic_median', 'bp_systolic_min', 'bp_systolic_range',
       'Calcium_max', 'Calcium_median', 'Calcium_min', 'Calcium_range',
       'Chloride_max', 'Chloride_median', 'Chloride_min',
       'Chloride_range', 'Creatinine_max', 'Creatinine_median',
       'Creatinine_min', 'Creatinine_range', 'Eosinophils_max',
       'Eosinophils_median', 'Eosinophils_min', 'Eosinophils_range',
       'Gender_mean', 'Glucose_max', 'Glucose_median', 'Glucose_min',
       'Glucose_range', 'hands_max', 'hands_median', 'hands_min',
       'hands_range', 'Hematocrit_max', 'Hematocrit_median',
       'Hematocrit_min', 'Hematocrit_range', 'Hemoglobin_max',
       'Hemoglobin_median', 'Hemoglobin_min', 'Hemoglobin_range',
       'leg_max', 'leg_median', 'leg_min', 'leg_range', 'Lymphocytes_max',
       'Lymphocytes_median', 'Lymphocytes_min', 'Lymphocytes_range',
       'Monocytes_max', 'Monocytes_median', 'Monocytes_min',
       'Monocytes_range', 'mouth_max', 'mouth_median', 'mouth_min',
       'mouth_range', 'onset_delta_mean', 'onset_site_mean',
       'Platelets_max', 'Platelets_median', 'Platelets_min',
       'Potassium_max', 'Potassium_median', 'Potassium_min',
       'Potassium_range', 'pulse_max', 'pulse_median', 'pulse_min',
       'pulse_range', 'Red.Blood.Cells..RBC._max',
       'Red.Blood.Cells..RBC._median', 'Red.Blood.Cells..RBC._min',
       'Red.Blood.Cells..RBC._range', 'respiratory_max',
       'respiratory_median', 'respiratory_min', 'respiratory_range',
       'Sodium_max', 'Sodium_median', 'Sodium_min', 'Sodium_range',
       'SubjectID', 'trunk_max', 'trunk_median', 'trunk_min',
       'trunk_range', 'Urine.Ph_max', 'Urine.Ph_median', 'Urine.Ph_min',
       'Urine.Ph_range', 'White.Blood.Cell..WBC._max',
       'White.Blood.Cell..WBC._median', 'White.Blood.Cell..WBC._min',
       'White.Blood.Cell..WBC._range'], dtype=object)

In [31]:
df_test.isnull().sum()

ID                               0
Age_mean                         0
Albumin_max                      0
Albumin_median                   0
Albumin_min                      0
                                ..
Urine.Ph_range                   0
White.Blood.Cell..WBC._max       0
White.Blood.Cell..WBC._median    0
White.Blood.Cell..WBC._min       0
White.Blood.Cell..WBC._range     0
Length: 131, dtype: int64

In [32]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2223 entries, 0 to 2222
Columns: 101 entries, ID to Urine.Ph_min
dtypes: float64(75), int64(26)
memory usage: 1.7 MB

In [33]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Columns: 131 entries, ID to White.Blood.Cell..WBC._range
dtypes: float64(92), int64(39)
memory usage: 80.0 KB

In [34]:
#columns don't match in test and train
#it is better to train your model with only significant features than to train it with all the features,
#including unnecessary ones.

In [35]:
X = [cols for cols in df_train.columns]

In [36]:
df_test = df_test[X]#same cols in test simillar to train

In [37]:
# X_Feature_cols = ['Age_mean','Albumin_median','ALSFRS_Total_median','ALT.SGPT._median','AST.SGOT._median','Basophils_median'
# ,'Bicarbonate_median','Bilirubin..total._median','Blood.Urea.Nitrogen..BUN._median', 'bp_diastolic_median', 'bp_systolic_median'
# ,'Calcium_median','Chloride_median','Creatinine_median','Eosinophils_median', 'Glucose_median','hands_median','Hematocrit_median','Hemoglobin_median'
# ,'leg_median','Lymphocytes_median','Monocytes_median','mouth_median','onset_delta_mean','onset_site_mean','Platelets_median'
# ,'Potassium_median','pulse_median','Red.Blood.Cells..RBC._median','respiratory_median','Sodium_median','SubjectID','trunk_median'
# ,'Urine.Ph_median','White.Blood.Cell..WBC._median']

In [38]:
Y_test = np.array(df_test.ALSFRS_slope)

In [39]:
df_test = np.array(df_test.drop(['ALSFRS_slope'],axis = 1))

In [40]:
Y_train = np.array(df_train.ALSFRS_slope)
df_train = np.array(df_train.drop(['ALSFRS_slope'],axis =1))

In [41]:
kmeans = KMeans(n_clusters= 2)

In [42]:
kmeans.fit(df_train)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=2, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [43]:
correct = 0
for i in range(len(df_test)):
    predict_me = np.array(df_test[i].astype(float))
    predict_me = predict_me.reshape(-1, len(predict_me))
    prediction = kmeans.predict(predict_me)
    if prediction[0] == Y_test[i]:
        correct += 1

print(correct/len(X))

0.009900990099009901

In [44]:
# Feature Engineering